name = "gorkbot"
language = "javascript"
service_id = ""

[scripts]
build = "npm run build"

[local_server]
[local_server.backends]
[local_server.backends.discord_api]
url = "https://discord.com/api"

[setup]
[setup.backends]
[setup.backends.discord_api]
address = "discord.com"
port = 443
